# Generated by Django 5.2.2 on 2025-07-08 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagotarjeta',
            options={'ordering': ['-fecha_transaccion'], 'verbose_name': 'Pago Tarjeta', 'verbose_name_plural': 'Pagos Tarjeta'},
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='codigo_transaccion',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='email_titular',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='nombre_titular',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='ultimos_digitos',
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='banco_emisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='fecha_transaccion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='numero_tarjeta_enmascarado',
            field=models.CharField(default='**** **** **** 0000', max_length=19),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='numero_transaccion',
            field=models.CharField(default='TXN000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='user_agent',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='codigo_autorizacion',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='ip_cliente',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.pedido'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='tipo_tarjeta',
            field=models.CharField(default='visa', max_length=20),
        ),
        migrations.AlterModelTable(
            name='pagotarjeta',
            table='catalogo_pagotarjeta',
        ),
        migrations.CreateModel(
            name='PagoTransbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=26, unique=True)),
                ('session_id', models.CharField(max_length=61)),
                ('token_ws', models.CharField(max_length=64)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('authorization_code', models.CharField(blank=True, max_length=6, null=True)),
                ('response_code', models.CharField(blank=True, max_length=2, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('accounting_date', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=2, null=True)),
                ('card_number', models.CharField(blank=True, max_length=4, null=True)),
                ('ip_cliente', models.GenericIPAddressField(default='127.0.0.1')),
                ('user_agent', models.TextField(default='Unknown')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.pedido')),
            ],
            options={
                'verbose_name': 'Pago Transbank',
                'verbose_name_plural': 'Pagos Transbank',
                'db_table': 'catalogo_pagotransbank',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(help_text='ID del producto en la API externa')),
                ('producto_codigo', models.CharField(max_length=50)),
                ('producto_nombre', models.CharField(max_length=200)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_compra_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('razon_cambio', models.TextField(blank=True, help_text='Motivo del cambio de precio', null=True)),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['producto_id', '-fecha_modificacion'], name='catalogo_hi_product_ff80dc_idx'), models.Index(fields=['usuario_modificacion', '-fecha_modificacion'], name='catalogo_hi_usuario_1d8660_idx')],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(help_text='Código único del local', max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal'), ('bodega', 'Bodega'), ('showroom', 'Showroom'), ('centro_distribucion', 'Centro de Distribución')], default='sucursal', max_length=25)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gerente', models.CharField(blank=True, max_length=200)),
                ('horario_atencion', models.TextField(help_text='Ej: Lunes a Viernes 9:00-18:00, Sábados 9:00-14:00')),
                ('permite_retiro', models.BooleanField(default=True, help_text='¿Permite retiro de productos?')),
                ('tiene_estacionamiento', models.BooleanField(default=False)),
                ('accesible_discapacitados', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('cerrado_temporal', 'Cerrado Temporalmente'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_apertura', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado', 'ciudad'], name='catalogo_lo_estado_a8a439_idx'), models.Index(fields=['tipo', 'estado'], name='catalogo_lo_tipo_2b6808_idx')],
            },
        ),
    ]
