"""
Django settings for market project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0u#a_*)3vx%_c!v1&f%nvbmc(=nx&cu6=eh=^%rceec9t*ao^h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Configuración de seguridad (ajustar cuando DEBUG=False)
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['tudominio.com', 'www.tudominio.com']
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalogo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'catalogo.middleware.AdminActionLoggingMiddleware',  # Agregar esta línea
    'catalogo.middleware.RoleMiddleware',  # Agregar nuevo middleware
]

ROOT_URLCONF = 'market.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],  # Usar tu carpeta 'template' existente
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Para usar MEDIA_URL en templates
            ],
        },
    },
]

WSGI_APPLICATION = 'market.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-cl'  # Cambiar a español chileno
TIME_ZONE = 'America/Santiago'  # Cambiar a zona horaria de Chile
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para producción

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Configuración de sesiones (importante para el carrito)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Almacena sesiones en la base de datos
SESSION_COOKIE_AGE = 1209600  # 2 semanas en segundos
SESSION_SAVE_EVERY_REQUEST = True  # Actualiza la sesión en cada petición
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # La sesión no expira al cerrar el navegador

# Configuración de API - Para integración con Spring Boot
API_URL = 'http://127.0.0.1:3309/api/productos'  # Ajusta el puerto según tu API
API_TIMEOUT = 10  # Tiempo de espera en segundos

# Configuración específica para la ferretería
FERRETERIA_CONFIG = {
    'NOMBRE_EMPRESA': 'Ferretería El Martillo',
    'RUT_EMPRESA': '12.345.678-9',
    'DIRECCION': 'Av. Providencia 123, Santiago',
    'TELEFONO': '+56 2 2345 6789',
    'EMAIL': 'contacto@ferreteriamartillo.cl',
    'HORARIO': 'Lunes a Viernes: 8:00 - 18:00, Sábados: 9:00 - 14:00',
    'COSTO_ENVIO_GRATIS': 50000,  # Envío gratis sobre $50.000
    'COSTO_ENVIO_NORMAL': 3000,   # Costo envío normal
}

# Configuración de mensajes (para notificaciones de Bootstrap)
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Configuración de logging para desarrollo y acciones administrativas
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'admin_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'admin_actions.log',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'admin_actions': {
            'handlers': ['admin_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'catalogo': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Crear directorio de logs si no existe
import os
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Configuración de Transbank para pagos
TRANSBANK_CONFIG = {
    'ENVIRONMENT': 'INTEGRATION',  # Cambiar a 'PRODUCTION' en producción
    'COMMERCE_CODE': '597055555532',  # Tu código de comercio
    'API_KEY': '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
}

# Configuración de pagos
PAYMENTS_CONFIG = {
    'ENABLE_TRANSBANK': True,
    'ENABLE_CASH_ON_DELIVERY': True,
    'ENABLE_BANK_TRANSFER': True,
    'MIN_AMOUNT_ONLINE_PAYMENT': 5000,  # Monto mínimo para pago online
}

# Configuración de locales
LOCALES_CONFIG = {
    'ALLOW_PICKUP': True,  # Permitir retiro en tienda
    'DEFAULT_PICKUP_TIME': 24,  # Horas para preparar pedido
    'CALCULATE_DISTANCE': False,  # Calcular distancia a locales
}
# Configuración de seguridad adicional
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True